import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider, ErrorBoundary } from '@rollbar/react';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const rollbarConfig = {
  accessToken: process.env.NEXT_PUBLIC_ROLLBAR_CLIENT_TOKEN,
  captureUncaught: true,
  captureUnhandledRejections: true,
  environment: 'production',
  server: {
    root: "https://nextjs-example-beta-ten.vercel.app/",
  },
  code_version: process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider config={rollbarConfig}>
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
        </Provider>
      </body>
    </html>
  );
}
